const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const Issue = require('../models/Issue');
const Community = require('../models/Community');
const { protect, requireModerator } = require('../middleware/auth');

// GET /api/issues/community/:communityId
router.get('/community/:communityId', protect, async (req, res, next) => {
  try {
    const { status, category, severity, page = 1, limit = 20 } = req.query;
    const query = { community: req.params.communityId };
    if (status) query.status = status;
    if (category) query.category = category;
    if (severity) query.severity = severity;

    const issues = await Issue.find(query)
      .populate('author', 'fullName neighbourhood')
      .populate('comments.author', 'fullName')
      .sort({ createdAt: -1 })
      .skip((page - 1) * limit)
      .limit(Number(limit));

    const total = await Issue.countDocuments(query);
    res.json({ issues, total });
  } catch (err) {
    next(err);
  }
});

// GET /api/issues/:id
router.get('/:id', protect, async (req, res, next) => {
  try {
    const issue = await Issue.findById(req.params.id)
      .populate('author', 'fullName neighbourhood')
      .populate('comments.author', 'fullName')
      .populate('attachedPoll');
    if (!issue) return res.status(404).json({ message: 'Issue not found' });
    res.json({ issue });
  } catch (err) {
    next(err);
  }
});

// POST /api/issues
router.post('/', protect, async (req, res, next) => {
  try {
    const { community, title, category, description, locationDescription, imageUrl, severity, affectedHouseholds } = req.body;
    const issue = await Issue.create({
      community, title, category, description, locationDescription,
      imageUrl, severity, affectedHouseholds, author: req.user._id,
    });
    await Community.findByIdAndUpdate(community, { $inc: { issueCount: 1 } });
    await issue.populate('author', 'fullName neighbourhood');
    res.status(201).json({ issue });
  } catch (err) {
    next(err);
  }
});

// POST /api/issues/:id/support
router.post('/:id/support', protect, async (req, res, next) => {
  try {
    const issue = await Issue.findById(req.params.id);
    if (!issue) return res.status(404).json({ message: 'Issue not found' });
    const supported = issue.supporters.includes(req.user._id);
    if (supported) {
      issue.supporters.pull(req.user._id);
    } else {
      issue.supporters.push(req.user._id);
    }
    issue.supportCount = issue.supporters.length;
    await issue.save();
    res.json({ supportCount: issue.supportCount, supported: !supported });
  } catch (err) {
    next(err);
  }
});

// POST /api/issues/:id/comments
router.post('/:id/comments', protect, async (req, res, next) => {
  try {
    const issue = await Issue.findById(req.params.id);
    if (!issue) return res.status(404).json({ message: 'Issue not found' });
    issue.comments.push({ author: req.user._id, text: req.body.text });
    await issue.save();
    await issue.populate('comments.author', 'fullName');
    res.status(201).json({ comment: issue.comments[issue.comments.length - 1] });
  } catch (err) {
    next(err);
  }
});

// PATCH /api/issues/:id/status (moderator)
router.patch('/:id/status', protect, async (req, res, next) => {
  try {
    const issue = await Issue.findByIdAndUpdate(
      req.params.id,
      { status: req.body.status },
      { new: true }
    );
    res.json({ issue });
  } catch (err) {
    next(err);
  }
});

// GET /api/issues/:id/report - generate PDF report
router.get('/:id/report', protect, async (req, res, next) => {
  try {
    const issue = await Issue.findById(req.params.id)
      .populate('author', 'fullName')
      .populate('comments.author', 'fullName');
    if (!issue) return res.status(404).json({ message: 'Issue not found' });

    const community = await Community.findById(issue.community);
    const { recipient } = req.query;

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="issue-report-${issue._id}.pdf"`);

    const doc = new PDFDocument({ margin: 50 });
    doc.pipe(res);

    // Header
    doc.fontSize(22).font('Helvetica-Bold').text('LIDA COMMUNITY ISSUE REPORT', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(11).font('Helvetica').fillColor('#555')
      .text('Generated by Lida – Lead where you live.', { align: 'center' });
    doc.moveDown(1);

    // Divider
    doc.moveTo(50, doc.y).lineTo(560, doc.y).strokeColor('#ccc').stroke();
    doc.moveDown(1);

    const field = (label, value) => {
      doc.fontSize(10).font('Helvetica-Bold').fillColor('#333').text(`${label}:`, { continued: true });
      doc.font('Helvetica').fillColor('#000').text(` ${value || 'N/A'}`);
    };

    field('Community', community?.name);
    field('State', community?.state);
    field('LGA', community?.lga);
    doc.moveDown(0.5);
    field('Issue Title', issue.title);
    field('Category', issue.category);
    field('Severity', issue.severity.toUpperCase());
    field('Status', issue.status);
    field('Date Reported', new Date(issue.createdAt).toLocaleDateString('en-NG', { year: 'numeric', month: 'long', day: 'numeric' }));
    field('Supporters', String(issue.supportCount));
    field('Comments', String(issue.comments.filter(c => !c.isHidden).length));
    field('Affected Households (estimated)', issue.affectedHouseholds > 0 ? String(issue.affectedHouseholds) : 'Not specified');

    if (recipient) {
      doc.moveDown(0.5);
      field('Suggested Recipient', recipient);
    }

    doc.moveDown(1);
    doc.fontSize(12).font('Helvetica-Bold').text('Description');
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica').text(issue.description);

    if (issue.locationDescription) {
      doc.moveDown(0.5);
      doc.fontSize(12).font('Helvetica-Bold').text('Location');
      doc.moveDown(0.3);
      doc.fontSize(10).font('Helvetica').text(issue.locationDescription);
    }

    // Key comments
    const visibleComments = issue.comments.filter(c => !c.isHidden).slice(0, 5);
    if (visibleComments.length > 0) {
      doc.moveDown(1);
      doc.fontSize(12).font('Helvetica-Bold').text('Key Resident Comments');
      doc.moveDown(0.3);
      visibleComments.forEach((c, i) => {
        doc.fontSize(10).font('Helvetica-Bold').text(`${i + 1}. ${c.author?.fullName || 'Resident'}:`);
        doc.font('Helvetica').text(c.text);
        doc.moveDown(0.3);
      });
    }

    // Footer
    doc.moveDown(2);
    doc.moveTo(50, doc.y).lineTo(560, doc.y).strokeColor('#ccc').stroke();
    doc.moveDown(0.5);
    doc.fontSize(9).fillColor('#888')
      .text('This report was generated through the Lida community platform. Lida is not an emergency service.', { align: 'center' });

    doc.end();
  } catch (err) {
    next(err);
  }
});

module.exports = router;
